

services:
  mysql-1:
    image: mysql:9.1
    deploy:
        replicas: 1
    ports:
        - 3301:3306
    volumes:
        - db-vol-1:/var/lib/mysql 
    environment:
        - MYSQL_ROOT_PASSWORD=mysqlPassword

  mysql-2:
    image: mysql:9.1
    deploy:
        replicas: 1
    ports:
        - 3302:3306
    volumes:
      - db-vol-2:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=mysqlPassword      

volumes:
  db-vol-1:
  db-vol-2:
  
